### ISSUE TITLE
NameError - uninitialized constant OpenID::Server::Server::DefaultNegotiator

### ISSUE THREAD

**Issue by Hiroyuki-Nagata** [openid/ruby-openid#100]
Hello, I'm using this module with Rails4.
But, I got following error message, 

```
F, [2016-07-07T10:50:02.936420 #21001] FATAL -- :
NameError - uninitialized constant OpenID::Server::Server::DefaultNegotiator:
  activesupport (4.2.6) lib/active_support/dependencies.rb:533:in `load_missing_constant'
  activesupport (4.2.6) lib/active_support/dependencies.rb:184:in `const_missing'
   () home/nagata/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/ruby-openid-5dd11301f004/lib/openid/server.rb:1319:in `initialize'
  app/controllers/openid_server_controller.rb:222:in `server'
  app/controllers/openid_server_controller.rb:21:in `index'
  app/controllers/openid_server_controller.rb:79:in `create'
  actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
```

It looks `DefaultNegotiator.copy()` is failed because of constants `DefaultNegotiator` is not defined.
```
      # op_endpoint is new in library version 2.0.
      def initialize(store, op_endpoint)
        @store = store
        @signatory = @@signatoryClass.new(@store)
        @encoder = @@encoderClass.new(@signatory)
        @decoder = @@decoderClass.new(self)
        @negotiator = DefaultNegotiator.copy()
        @op_endpoint = op_endpoint
      end
```

I would like to ask why this is happen.
If it's bug, I can provide some patches.

**Comment by Hiroyuki-Nagata** [comment]
Sorry, I realized it's my fault.
I created some models with namespace `OpenID::` , it disturbed module definition.

Thank you
