### ISSUE TITLE
encoding problems with 2.3.0 test suite

### ISSUE THREAD

**Issue by ktdreyer** [openid/ruby-openid#60]
I've encountered two test failures related to encoding problems.

Fedora's build system does not set the `LANG` variable. You can duplicate this as follows:

```
export LANG=
testrb -Ilib test
```

Here's the results:

```
Run options: -Ilib
# Running tests:
.....................................E.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................E.
Finished tests in 14.175624s, 61.8668 tests/s, 453.1723 assertions/s.
  1) Error:
LinkParseTestCase#test_linkparse:
ArgumentError: invalid byte sequence in US-ASCII
    /builddir/build/BUILD/ruby-openid-2.3.0/usr/share/gems/gems/ruby-openid-2.3.0/test/test_linkparse.rb:57:in `split'
    /builddir/build/BUILD/ruby-openid-2.3.0/usr/share/gems/gems/ruby-openid-2.3.0/test/test_linkparse.rb:57:in `test_linkparse'
  2) Error:
TrustRootTest#test_trustroots:
ArgumentError: invalid byte sequence in US-ASCII
    /builddir/build/BUILD/ruby-openid-2.3.0/usr/share/gems/gems/ruby-openid-2.3.0/test/test_trustroot.rb:37:in `split'
    /builddir/build/BUILD/ruby-openid-2.3.0/usr/share/gems/gems/ruby-openid-2.3.0/test/test_trustroot.rb:37:in `test_trustroots'
877 tests, 6424 assertions, 0 failures, 2 errors, 0 skips
ruby -v: ruby 2.0.0p247 (2013-06-27 revision 41674) [armv7hl-linux]
```

When I set `LANG` to `en_US.utf8`, the tests pass.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
